**Import Pandas as pd**

In [50]:
import pandas as pd

**Read the CSV File**

In [8]:
movie_data = pd.read_csv('IMDB-Movie-Data.csv')

**View a IMDB Data**

In [9]:
movie_data.head()

   Rank                    Title  ... Revenue (Millions) Metascore
0     1  Guardians of the Galaxy  ...             333.13      76.0
1     2               Prometheus  ...             126.46      65.0
2     3                    Split  ...             138.12      62.0
3     4                     Sing  ...             270.32      59.0
4     5            Suicide Squad  ...             325.02      40.0

[5 rows x 12 columns]

**Basic Information about IMDB Data**

In [10]:
movie_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

In [11]:
movie_data.shape

(1000, 12)

In [12]:
movie_data.describe()

              Rank         Year  ...  Revenue (Millions)   Metascore
count  1000.000000  1000.000000  ...          872.000000  936.000000
mean    500.500000  2012.783000  ...           82.956376   58.985043
std     288.819436     3.205962  ...          103.253540   17.194757
min       1.000000  2006.000000  ...            0.000000   11.000000
25%     250.750000  2010.000000  ...           13.270000   47.000000
50%     500.500000  2014.000000  ...           47.985000   59.500000
75%     750.250000  2016.000000  ...          113.715000   72.000000
max    1000.000000  2016.000000  ...          936.630000  100.000000

[8 rows x 7 columns]

**Data Selection**

In [13]:
cols = movie_data[['Title','Genre','Actors','Director','Rating']]

In [14]:
cols

                       Title  ... Rating
0    Guardians of the Galaxy  ...    8.1
1                 Prometheus  ...    7.0
2                      Split  ...    7.3
3                       Sing  ...    7.2
4              Suicide Squad  ...    6.2
..                       ...  ...    ...
995     Secret in Their Eyes  ...    6.2
996          Hostel: Part II  ...    5.5
997   Step Up 2: The Streets  ...    6.2
998             Search Party  ...    5.6
999               Nine Lives  ...    5.3

[1000 rows x 5 columns]

In [26]:
movie_data.iloc[25:31][['Title','Genre','Actors','Rating','Revenue (Millions)']]

                      Title                   Genre  ... Rating  Revenue (Millions)
25          Paris pieds nus                  Comedy  ...    6.8                 NaN
26  Bahubali: The Beginning  Action,Adventure,Drama  ...    8.3                6.50
27               Dead Awake         Horror,Thriller  ...    4.7                0.01
28                 Bad Moms                  Comedy  ...    6.2              113.08
29         Assassin's Creed  Action,Adventure,Drama  ...    5.9               54.65
30                 Why Him?                  Comedy  ...    6.3               60.31

[6 rows x 5 columns]

**Data Selection using Condition**

In [67]:
movie_data[((movie_data['Year'] >= 2010) & (movie_data['Year'] <= 2016)) & (movie_data['Rating'] < 6.0)].tail()

     Rank                     Title  ... Revenue (Millions) Rating_category
985   986             Your Highness  ...          21.560000             Bad
986   987       Final Destination 5  ...          42.580000             Bad
993   994  Resident Evil: Afterlife  ...          60.130000             Bad
998   999              Search Party  ...          82.956376             Bad
999  1000                Nine Lives  ...          19.640000             Bad

[5 rows x 12 columns]

**Find Missing Data**

In [28]:
movie_data.isnull()

      Rank  Title  Genre  ...  Votes  Revenue (Millions)  Metascore
0    False  False  False  ...  False               False      False
1    False  False  False  ...  False               False      False
2    False  False  False  ...  False               False      False
3    False  False  False  ...  False               False      False
4    False  False  False  ...  False               False      False
..     ...    ...    ...  ...    ...                 ...        ...
995  False  False  False  ...  False                True      False
996  False  False  False  ...  False               False      False
997  False  False  False  ...  False               False      False
998  False  False  False  ...  False                True      False
999  False  False  False  ...  False               False      False

[1000 rows x 12 columns]

In [29]:
movie_data.isnull().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

**Dealing with missing Data**

In [44]:
movie_data.dropna(axis=0).head()

   Rank                    Title  ...   Votes Revenue (Millions)
0     1  Guardians of the Galaxy  ...  757074             333.13
1     2               Prometheus  ...  485820             126.46
2     3                    Split  ...  157606             138.12
3     4                     Sing  ...   60545             270.32
4     5            Suicide Squad  ...  393727             325.02

[5 rows x 11 columns]

In [45]:
movie_data.dropna(axis=1).head()

   Rank                    Title  ... Rating   Votes
0     1  Guardians of the Galaxy  ...    8.1  757074
1     2               Prometheus  ...    7.0  485820
2     3                    Split  ...    7.3  157606
3     4                     Sing  ...    7.2   60545
4     5            Suicide Squad  ...    6.2  393727

[5 rows x 10 columns]

In [46]:
revenue_mean = movie_data['Revenue (Millions)'].mean()

In [47]:
print("The mean revenue is: ", revenue_mean)

The mean revenue is:  82.95637614678897

In [48]:
movie_data['Revenue (Millions)'].fillna(revenue_mean, inplace=True)

In [49]:
movie_data['Revenue (Millions)'].isnull().sum()

0

**Groupby Operation**

In [72]:
movie_data.groupby('Director')[['Rating']].mean().head()

                     Rating
Director
Aamir Khan              8.5
Abdellatif Kechiche     7.8
Adam Leon               6.5
Adam McKay              7.0
Adam Shankman           6.3

In [76]:
movie_data.groupby('Director')[['Rating']].mean().sort_values(['Rating'], ascending=False).head()

                                  Rating
Director
Nitesh Tiwari                       8.80
Christopher Nolan                   8.68
Makoto Shinkai                      8.60
Olivier Nakache                     8.60
Florian Henckel von Donnersmarck    8.50

**To find Top Movies**

In [77]:
def rating_group(rating):
    if rating >= 7.5:
        return 'Good'
    elif rating >= 6.0:
        return 'Average'
    else:
        return 'Bad'

In [78]:
movie_data['Rating_category'] = movie_data['Rating'].apply(rating_group)

In [79]:
movie_data[['Title','Director','Rating','Rating_category']].head(10)

                     Title              Director  Rating Rating_category
0  Guardians of the Galaxy            James Gunn     8.1            Good
1               Prometheus          Ridley Scott     7.0         Average
2                    Split    M. Night Shyamalan     7.3         Average
3                     Sing  Christophe Lourdelet     7.2         Average
4            Suicide Squad            David Ayer     6.2         Average
5           The Great Wall           Yimou Zhang     6.1         Average
6               La La Land       Damien Chazelle     8.3            Good
7                 Mindhorn            Sean Foley     6.4         Average
8       The Lost City of Z            James Gray     7.1         Average
9               Passengers         Morten Tyldum     7.0         Average

**What is the title of Ridley Scott?**

In [84]:
movie_data[movie_data['Director']=='Ridley Scott']['Title']

1                  Prometheus
102               The Martian
387                Robin Hood
470         American Gangster
516    Exodus: Gods and Kings
521             The Counselor
530               A Good Year
737              Body of Lies
Name: Title, dtype: object